const BUILDINGS = {
  greatHall: {
    name: "Great Hall",
    description: "The heart of your domain. Upgrading this majestic hall increases the speed of all other construction projects within the village.",
    baseCost: { wood: 90, clay: 80, stone: 70 },
    costMultiplier: 1.25,
    timeMultiplier: 1.28,
    growthFactor: 0.03,
    baseBuildTime: 120,
    basePop: 5,
    popMultiplier: 1.18,
    maxLevel: 30,
    pointValue: 10,
    pointFactor: 1.26,
    requirements: {}
  },

  woodFarm: {
    name: "Wood Farm",
    description: "Deep within the ancient groves, hardy woodsmen fell timber to fuel your kingdom's expansion and provide essential building materials.",
    baseCost: { wood: 50, clay: 40, stone: 30 },
    costMultiplier: 1.18,
    timeMultiplier: 1.31,
    growthFactor: 1.15,
    baseBuildTime: 60,
    basePop: 4,
    popMultiplier: 1.17,
    productionBase: 80,
    maxLevel: 30,
    pointValue: 8,
    pointFactor: 1.21,
    requirements: {}
  },

  clayFarm: {
    name: "Clay Farm",
    description: "Laborers toil in the riverbanks to harvest rich clay, vital for crafting the sturdy bricks and pottery required by your growing populace.",
    baseCost: { wood: 40, clay: 50, stone: 30 },
    costMultiplier: 1.18,
    timeMultiplier: 1.31,
    growthFactor: 1.15,
    baseBuildTime: 60,
    basePop: 4,
    popMultiplier: 1.17,
    productionBase: 80,
    maxLevel: 30,
    pointValue: 8,
    pointFactor: 1.21,
    requirements: {}
  },

  stoneFarm: {
    name: "Stone Farm",
    description: "Masons extract massive blocks of granite from the earth's crust to reinforce your structures and raise impenetrable defenses.",
    baseCost: { wood: 40, clay: 30, stone: 25 },
    costMultiplier: 1.18,
    timeMultiplier: 1.31,
    growthFactor: 1.15,
    baseBuildTime: 60,
    basePop: 4,
    popMultiplier: 1.17,
    productionBase: 80,
    maxLevel: 30,
    pointValue: 8,
    pointFactor: 1.21,
    requirements: {}
  },

  barracks: {
    name: "Barracks",
    description: "The primary training ground for your infantry. Here, peasants are forged into disciplined soldiers ready to die for your honor.",
    baseCost: { wood: 200, clay: 170, stone: 90 },
    costMultiplier: 1.27,
    timeMultiplier: 1.5,
    growthFactor: 0.02,
    baseBuildTime: 100,
    basePop: 7,
    popMultiplier: 1.2,
    maxLevel: 25,
    pointValue: 8,
    pointFactor: 1.26,
    requirements: { greatHall: 3 }
  },

  stable: {
    name: "Stable",
    description: "A sanctuary for warhorses and riders. Upgrading the stables allows for the swift training of devastating cavalry units.",
    baseCost: { wood: 300, clay: 350, stone: 150 },
    costMultiplier: 1.27,
    timeMultiplier: 1.5,
    growthFactor: 0.02,
    baseBuildTime: 130,
    basePop: 12,
    popMultiplier: 1.25,
    maxLevel: 20,
    pointValue: 12,
    pointFactor: 1.26,
    requirements: { greatHall: 10, barracks: 5 }
  },

  workshop: {
    name: "Workshop",
    description: "The birthplace of siege warfare. Here, master engineers construct devastating rams and catapults to shatter the gates of those who defy your rule.",
    baseCost: { wood: 300, clay: 350, stone: 400 },
    costMultiplier: 1.8,
    timeMultiplier: 1.35,
    growthFactor: 0.02,
    baseBuildTime: 720,
    basePop: 15,
    popMultiplier: 1.25,
    maxLevel: 15,
    pointValue: 14,
    pointFactor: 1.28,
    requirements: { greatHall: 10, barracks: 10, stable: 5 }
  },

  hospital: {
    name: "Hospital",
    description: "A sanctuary of healing where the wounded return from the brink of death. Higher levels increase the percentage of fallen troops recovered after battle.",
    baseCost: { wood: 450, clay: 400, stone: 500 },
    costMultiplier: 1.35,
    timeMultiplier: 1.4,
    growthFactor: 0.05,
    baseBuildTime: 900,
    basePop: 10,
    popMultiplier: 1.2,
    recoveryBase: 0.05,
    maxLevel: 15,
    pointValue: 15,
    pointFactor: 1.25,
    requirements: { greatHall: 15, barracks: 10 }
  },

  dragonsPit: {
    name: "Dragons Pit",
    description: "A terrifying subterranean lair where ancient fire-drakes are beckoned. Only the most legendary kingdoms can hope to house such primal power.",
    baseCost: { wood: 2500, clay: 2000, stone: 5000 },
    costMultiplier: 2.2,
    timeMultiplier: 1.8,
    growthFactor: 0.5,
    baseBuildTime: 3600,
    basePop: 50,
    popMultiplier: 1.5,
    maxLevel: 5,
    pointValue: 250,
    pointFactor: 1.5,
    requirements: { greatHall: 25, workshop: 15, palace: 1 }
  },

  church: {
    name: "Church",
    description: "A beacon of faith that bolsters the resolve of your people. The divine presence increases the loyalty and morale of troops within its influence.",
    baseCost: { wood: 600, clay: 400, stone: 800 },
    costMultiplier: 1.5,
    timeMultiplier: 1.6,
    growthFactor: 1,
    baseBuildTime: 1200,
    basePop: 20,
    popMultiplier: 1.3,
    maxLevel: 3,
    pointValue: 100,
    pointFactor: 1.4,
    requirements: { greatHall: 20, farm: 20 }
  },

  palace: {
    name: "Palace",
    description: "The ultimate symbol of sovereignty. A grand palace allows you to educate Noblemen to conquer and annex new villages for your empire.",
    baseCost: { wood: 1000, clay: 1200, stone: 1500 },
    costMultiplier: 2.0,
    timeMultiplier: 1.7,
    growthFactor: 0.1,
    baseBuildTime: 1800,
    basePop: 80,
    popMultiplier: 1.4,
    maxLevel: 3,
    pointValue: 200,
    pointFactor: 1.35,
    requirements: { greatHall: 20, market: 20, stable: 20 }
  },

  reunionPoint: {
    name: "Reunion Point",
    description: "The central gathering spot for your generals. Here you organize movements, send support, and launch calculated strikes against your foes.",
    baseCost: { wood: 20, clay: 40, stone: 10 },
    costMultiplier: 1.1,
    timeMultiplier: 1.1,
    growthFactor: 0.01,
    baseBuildTime: 30,
    basePop: 0,
    popMultiplier: 1.0,
    maxLevel: 1,
    pointValue: 2,
    pointFactor: 1,
    requirements: {}
  },

  statue: {
    name: "Statue",
    description: "An effigy of your kingdom's Paladin. Presence of this monument allows you to summon a legendary hero to lead your armies.",
    baseCost: { wood: 220, clay: 220, stone: 220 },
    costMultiplier: 1,
    timeMultiplier: 1,
    growthFactor: 0,
    baseBuildTime: 150,
    basePop: 10,
    popMultiplier: 1,
    maxLevel: 1,
    pointValue: 24,
    pointFactor: 1,
    requirements: {}
  },

  arena: {
    name: "Arena",
    description: "A place of sport and blood. Gladiatorial matches held here keep the populace entertained and hone the reflexes of your combatants.",
    baseCost: { wood: 500, clay: 300, stone: 700 },
    costMultiplier: 1.4,
    timeMultiplier: 1.45,
    growthFactor: 0.08,
    baseBuildTime: 1200,
    basePop: 25,
    popMultiplier: 1.22,
    maxLevel: 20,
    pointValue: 18,
    pointFactor: 1.25,
    requirements: { greatHall: 15, barracks: 15 }
  },

  watchTower: {
    name: "Watch Tower",
    description: "Extends the vision of your scouts. A higher tower allows for early detection of incoming raids and hidden enemy movements.",
    baseCost: { wood: 150, clay: 100, stone: 250 },
    costMultiplier: 1.3,
    timeMultiplier: 1.3,
    growthFactor: 0.2,
    baseBuildTime: 500,
    basePop: 5,
    popMultiplier: 1.15,
    maxLevel: 20,
    pointValue: 10,
    pointFactor: 1.2,
    requirements: { greatHall: 5, wall: 5 }
  },

  library: {
    name: "Library",
    description: "A repository of forgotten scrolls. Scholars here research technologies that reduce resource costs and improve village efficiency.",
    baseCost: { wood: 300, clay: 400, stone: 200 },
    costMultiplier: 1.25,
    timeMultiplier: 1.3,
    growthFactor: 0.04,
    baseBuildTime: 800,
    basePop: 8,
    popMultiplier: 1.18,
    maxLevel: 20,
    pointValue: 12,
    pointFactor: 1.22,
    requirements: { greatHall: 10, market: 5 }
  },

  market: {
    name: "Market",
    description: "A bustling hub of trade where merchants barter goods. Leveling the market provides more merchants to facilitate resource exchange with allies.",
    baseCost: { wood: 80, clay: 90, stone: 70 },
    costMultiplier: 1.25,
    timeMultiplier: 1.3,
    growthFactor: 1,
    baseBuildTime: 240,
    basePop: 5,
    popMultiplier: 1.17,
    merchantsBase: 1,
    maxLevel: 25,
    pointValue: 6,
    pointFactor: 1.1,
    requirements: { greatHall: 5 }
  },

  farm: {
    name: "Farm",
    description: "Providing the grain and livestock necessary to sustain your village. The larger the farm, the greater the population your village can support.",
    baseCost: { wood: 45, clay: 40, stone: 30 },
    costMultiplier: 1.3,
    timeMultiplier: 1.15,
    growthFactor: 1.23,
    baseBuildTime: 60,
    populationBase: 60,
    maxLevel: 30,
    pointValue: 3,
    pointFactor: 1.1,
    requirements: {}
  },

  warehouse: {
    name: "Warehouse",
    description: "A vast storage complex to protect your resources from the elements and raiding parties. Higher levels increase total resource capacity.",
    baseCost: { wood: 60, clay: 50, stone: 40 },
    costMultiplier: 1.26,
    timeMultiplier: 1.2,
    growthFactor: 1.25,
    baseBuildTime: 80,
    basePop: 2,
    popMultiplier: 1.1,
    storageBase: 1000,
    maxLevel: 30,
    pointValue: 4,
    pointFactor: 1.1,
    requirements: {}
  },

  wall: {
    name: "Wall",
    description: "A ring of stone and timber that shields your people. The wall significantly boosts the defensive capabilities of your stationed troops.",
    baseCost: { wood: 50, clay: 100, stone: 200 },
    costMultiplier: 1.4,
    timeMultiplier: 1.4,
    growthFactor: 1.02,
    baseBuildTime: 400,
    basePop: 5,
    popMultiplier: 1.1,
    defenseBonusBase: 0.05,
    maxLevel: 20,
    pointValue: 5,
    pointFactor: 1.1,
    requirements: { greatHall: 3 }
  },
};

module.exports = BUILDINGS;